### ISSUE TITLE
PyPi Release

### ISSUE THREAD

**Issue by alichtman** [sdushantha/down#1]

**Comment by sdushantha** [comment]
I would do it, but I have never managed to successfully do it

**Comment by alichtman** [comment]
Read [this](https://peterdowns.com/posts/first-time-with-pypi.html), and lemme know if you have any questions! I've done it a few times.

**Comment by vascowhite** [comment]
I can help with this if you wish. If you want me to, assign the issue to me, if not, no problem :)

**Comment by sdushantha** [comment]
@vascowhite Yes please! That would be a huge help

**Comment by sdushantha** [comment]
@vascowhite your name is not coming
![screen shot 2018-06-08 at 08 08 40](https://user-images.githubusercontent.com/27065646/41141682-40315032-6af3-11e8-945c-26fa76c31e0b.png)
 up when i try to assign it to you.

**Comment by vascowhite** [comment]
I think you have to add me as a collaborator in [settings/collaborators](https://github.com/sdushantha/down/settings/collaboration).

Don't worry if you don't want to that, I can still go ahead and help.
