### ISSUE TITLE
Python 3.6 syntax error

### ISSUE THREAD

**Issue by vascowhite** [sdushantha/down#2]
>  File "down.py", line 6
> SyntaxError: Non-ASCII character '\xe2' in file down.py on line 6, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

This is easily fixed, I will submit a pull request for it.
Nice little app :)

**Comment by sdushantha** [comment]
Thanks :)

Ok. I will we waiting for your PR :)
